### ISSUE TITLE
Unable to decode input

### ISSUE THREAD

**Issue by pushline** [Intervention/image-laravel#10]
Not a bug but a question on what i'm doing wrong here.

I went by the getting started section and im having the error on the title.
My code is literally just this:
```
Route::get('/1234', function ()
{
    $image = Image::read('facebook.png');
});
```

In my `public` folder i have a facebook.png image aswell.

**Comment by olivervogel** [comment]
I think you need to be more specific about the file path:

```php
// reads from Laravel's public directory if you have your code in "routes/web.php" for example
$image = Image::read(__DIR__ . '/../public/facebook.png'); 
```

Or better use the Laravel helper:

```php
// reads from Laravel's public directory no matter what
$image = Image::read(public_path('facebook.png')); 
```
