### ISSUE TITLE
Move PHPDoc to class level

### ISSUE THREAD

**Issue by ben221199** [Intervention/image-laravel#2]
The PHPDoc at the following line should be moved to class level: https://github.com/Intervention/image-laravel/blob/eb6f2478cb646eadfbc32941ef92647f5c4893ac/src/Facades/Image.php#L12

Because they are now at method level (which is strange for `@method` PHPDoc), they are not used by the IDE.

**Comment by diamond-edge** [comment]
Besides this, the methods should be `static`.

**Comment by olivervogel** [comment]
Thanks guys.
