### ISSUE TITLE
Error when Installing package

### ISSUE THREAD

**Issue by sgtcoder** [Intervention/image-laravel#7]
**Describe the bug**
Error when Installing package:
```
Illuminate\Container\EntryNotFoundException 
Intervention\Image\ImageManager
at vendor/laravel/framework/src/Illuminate/Container/Container.php:740
```

**Code Example**
```
composer require intervention/image-laravel
```

**Expected behavior**
For the package to not error out during installation

**Images**
![image](https://github.com/Intervention/image-laravel/assets/2577827/77c3b975-fac3-4f0d-a5ee-2e333c8d9fb8)

**Environment (please complete the following information):**
 - PHP Version: 8.3
 - OS: Debian 12
 - Intervention Image Version: 1.2
 - GD or Imagick: Both

**Comment by olivervogel** [comment]
This appears to be a local problem. The error message tells me that something in the Laravel dependency injection container seems to be going wrong and it might be a circular dependency. Which Laravel version are you using?

**Comment by sgtcoder** [comment]
Laravel 11

**Comment by olivervogel** [comment]
As I said there seems something wrong with your dependencies. Unfortunately, I can't help you any further.
