### ISSUE TITLE
Not working in Laravel 11

### ISSUE THREAD

**Issue by ubedthaheem** [Intervention/image-laravel#8]
**Describe the bug**
While implementing this package into my Laravel 11 project, it did not worked.
In laravel 11, `config/providers.php` file I added `Intervention\Image\Laravel\ImageServiceProvider::class` as a service provider and used `use Intervention\Image\Laravel\Facades\Image;` in my Controller, but that not worked.
Error says: `Call to undefined method Intervention\Image\ImageManager::make()`

**Code Example**

`namespace App\Http\Controllers\Admin;`
`use App\Http\Controllers\Controller;`
`use Intervention\Image\Laravel\Facades\Image;`
`class MediaController extends Controller {
       private function uploadImage($file, $folderPath) {
        
        $maxSize = 100 * 1024; // 10 MB in bytes 79130
        $minWidth = 10;
        $minHeight = 10;
    
        if ($file->getSize() > $maxSize) {
            return ['error' => true, 'message' => 'File size exceeds the maximum allowed size (10 MB or '.$maxSize.' bytes). Your image size is '.$file->getSize()];
        }

        $image = Image::make($file); **// here is ERROR**
        $width = $image->width();
        $height = $image->height();

        if ($width < $minWidth || $height < $minHeight) {
            return ['error' => true, 'message' => 'Image dimensions must be at least 10x10 pixels.'];
        }

        // Generate random name for the image
        $imageName = date('dmY') . '_' . uniqid() . '.' . $file->getClientOriginalExtension();

        // Upload original image
        $fullPath = $folderPath ? "storage/images/$folderPath/$imageName" : "storage/images/$imageName";
        $file->storeAs($folderPath ? "public/images/$folderPath" : "public/images", $imageName);
 
        return [
            'size' => $file->getSize(),
            'file_name' => $imageName,
            'full_path' => $fullPath,
            'mime_type' => $file->getMimeType()
        ];
    }
    }
`

**Expected behavior**
This code 

**Images**
![Screenshot 2024-04-18 125004](https://github.com/Intervention/image-laravel/assets/16397652/0b17d429-f702-4ef4-b587-07e84eb8778b)

**Environment (please complete the following information):**
 - PHP Version: 8.2
 - OS: Windows
 - Intervention Image Version: `"intervention/image-laravel": "^1.2",`

**Comment by olivervogel** [comment]
That's because `ImageManager::make()` is an Intervention Image Version 2 method. The package 'intervention/image-laravel` only supports Version 3. You need to upgrade your calls. More details on upgrading are available here: https://image.intervention.io/v3/introduction/upgrade

**Comment by arkdev1** [comment]
> That's because `ImageManager::make()` is an Intervention Image Version 2 method. The package 'intervention/image-laravel` only supports Version 3. You need to upgrade your calls. More details on upgrading are available here: https://image.intervention.io/v3/introduction/upgrade

```log

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - intervention/image-laravel[0.0.1, ..., 0.0.3, 1.0.0, ..., 1.0.1] require illuminate/support ^10.0 -> found illuminate/support[v10.0.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.
    - intervention/image-laravel 1.1.0 requires illuminate/support ^8|^9|^10 -> found illuminate/support[v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.
    - intervention/image-laravel 1.2.0 requires intervention/image ^3 -> found intervention/image[3.0.0-alpha.1, ..., 3.7.2] but the package is fixed to dev-main (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - intervention/image-laravel[dev-main, 1.3.0] require intervention/image ^3.7 -> found intervention/image[3.7.0, 3.7.1, 3.7.2] but the package is fixed to dev-main (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires intervention/image-laravel * -> satisfiable by intervention/image-laravel[dev-main, 0.0.1, 0.0.2, 0.0.3, 1.0.0, ..., 1.3.0, 9999999-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require intervention/image-laravel:*" to figure out if any version is installable, or "composer require intervention/image-laravel:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.


```
